version: 0.2

phases:

  install:
    commands:
      - "curl -s https://releases.hashicorp.com/terraform/1.3.6/terraform_1.3.6_linux_amd64.zip -o terraform.zip"
      - "unzip terraform.zip -d /usr/local/bin"
      - "chmod 755 /usr/local/bin/terraform"
      - "mv $CODEBUILD_SRC_DIR_TerraformPlan/terraform/${env}-terraform.tfplan terraform"
  pre_build:
    commands:
      - "echo env: $env"
      - "cd terraform ; terraform init -backend-config=../${env}.tfbackend -reconfigure"

  build:
    commands:
      - "cd terraform ; terraform apply ${env}-terraform.tfplan"
