name: Steampipe Azure Benchmark
on:
  # run a workflow manually on demand
  workflow_dispatch:
  # runs on the 7th, 14th, 21st and 28th day of every month at 04:00 UTC i.e., 09:30 AM IST
  schedule:
    - cron: "0 4 7,14,21,28 * *"

# These permissions are needed to interact with GitHub's OIDC Token endpoint.
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  azure:
    name: Steampipe Azure Demo
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout working branch"
        uses: actions/checkout@v3

      - name: "Az CLI login"
        id: config-azure-auth
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.OIDC_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.OIDC_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.OIDC_AZURE_SUBSCRIPTION_ID }}

      - name: "Install Steampipe cli and plugin"
        id: steampipe-installation
        run: |

          # Install Steampipe CLI
          sudo /bin/sh -c "$(curl -fsSL https://raw.githubusercontent.com/turbot/steampipe/main/install.sh)"
          # Check steampipe version
          steampipe -v
          # Install Azure and AzureAD plugins
          steampipe plugin install azure
          steampipe plugin install azuread

      - name: "Run Steampipe benchmark"
        id: steampipe-benchmark
        run: |

          # Install the Steampipe Azure Compliance mod
          steampipe mod install github.com/turbot/steampipe-mod-azure-compliance
          cd .steampipe/mods/github.com/turbot/steampipe-mod-azure-compliance*
          # Run the Azure CIS v1.5.0 benchmark
          steampipe check benchmark.cis_v150 --export=steampipe_azure_cis_v150_"$(date +"%d_%B_%Y")".html --output=none

      - name: "Slack Notification"
        id: slack-upload
        env:
          slack_channel: ${{ secrets.OIDC_SLACK_CHANNEL_ID }}
          slack_token: ${{ secrets.OIDC_SLACK_OAUTH_ACCESS_TOKEN }}
        run: |

          cd .steampipe/mods/github.com/turbot/steampipe-mod-azure-compliance*
          curl -F file=@"steampipe_azure_cis_v150_"$(date +"%d_%B_%Y")".html" -F "initial_comment=Steampipe Azure CIS v150 Benchmark" -F "title=steampipe_azure_cis_v150_"$(date +"%d_%B_%Y")".html" -F channels=$slack_channel -H "Authorization: Bearer $slack_token " https://slack.com/api/files.upload -s -o /dev/null

      - name: Cleanup Steampipe files
        id: cleanup
        run: rm -rf ~/.steampipe && rm -rf .steampipe
