name: Steampipe GCP Benchmark
on:
  # run a workflow manually on demand
  workflow_dispatch:
  # runs on the 7th, 14th, 21st and 28th day of every month at 04:00 UTC i.e., 09:30 AM IST
  schedule:
    - cron: "0 4 7,14,21,28 * *"

# These permissions are needed to interact with GitHub's OIDC Token endpoint.
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  gcp:
    name: Steampipe GCP Demo
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout working branch"
        uses: actions/checkout@v3

      - name: "Configure GCP credentials"
        id: config-gcp-auth
        uses: "google-github-actions/auth@v0"
        with:
          create_credentials_file: "true"
          workload_identity_provider: ${{ secrets.OIDC_GCP_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.OIDC_GCP_SERVICE_ACCOUNT }}
          access_token_lifetime: 900s

      - name: "Install Steampipe cli and plugin"
        id: steampipe-installation
        run: |

          # Install Steampipe CLI
          sudo /bin/sh -c "$(curl -fsSL https://raw.githubusercontent.com/turbot/steampipe/main/install.sh)"
          # Check steampipe version
          steampipe -v
          # Install GCP plugin
          steampipe plugin install gcp

      - name: "Run Steampipe benchmark"
        id: steampipe-benchmark
        run: |

          export CLOUDSDK_CORE_PROJECT=${{ secrets.OIDC_GCP_PROJECT }}
          # Install the Steampipe GCP Compliance mod
          steampipe mod install github.com/turbot/steampipe-mod-gcp-compliance
          cd .steampipe/mods/github.com/turbot/steampipe-mod-gcp-compliance*
          # Run the GCP CIS v1.3.0 benchmark
          steampipe check benchmark.cis_v130 --export=steampipe_gcp_cis_v130_"$(date +"%d_%B_%Y")".html --output=none

      - name: "Slack Notification"
        id: slack-upload
        env:
          slack_channel: ${{ secrets.OIDC_SLACK_CHANNEL_ID }}
          slack_token: ${{ secrets.OIDC_SLACK_OAUTH_ACCESS_TOKEN }}
        run: |

          cd .steampipe/mods/github.com/turbot/steampipe-mod-gcp-compliance*
          curl -F file=@"steampipe_gcp_cis_v130_"$(date +"%d_%B_%Y")".html" -F "initial_comment=Steampipe GCP CIS v130 Benchmark" -F "title=steampipe_gcp_cis_v130_"$(date +"%d_%B_%Y")".html" -F channels=$slack_channel -H "Authorization: Bearer $slack_token " https://slack.com/api/files.upload -s -o /dev/null

      - name: Cleanup Steampipe files
        id: cleanup
        run: rm -rf ~/.steampipe && rm -rf .steampipe
