name: Steampipe AWS Benchmark
on:
  # run a workflow manually on demand
  workflow_dispatch:
  # runs on the 7th, 14th, 21st and 28th day of every month at 04:00 UTC i.e., 09:30 AM IST
  schedule:
    - cron: "0 4 7,14,21,28 * *"

# These permissions are needed to interact with GitHub's OIDC Token endpoint.
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  aws:
    name: Steampipe AWS Demo
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout working branch"
        uses: actions/checkout@v3

      - name: "Configure AWS credentials"
        id: config-aws-auth
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: ${{ secrets.OIDC_AWS_ROLE_TO_ASSUME }}
          role-session-name: "steampipe-demo"
          role-duration-seconds: 900
          aws-region: "us-east-1"
          # Steampipe benchmark runs against this region unless a connection is specified in aws.spc file. More details at https://hub.steampipe.io/plugins/turbot/aws#credentials-from-environment-variables

      - name: "Install Steampipe cli and plugin"
        id: steampipe-installation
        run: |

          # Install Steampipe CLI
          sudo /bin/sh -c "$(curl -fsSL https://raw.githubusercontent.com/turbot/steampipe/main/install.sh)"
          # Check steampipe version
          steampipe -v 
          # Install AWS plugin
          steampipe plugin install aws

      - name: "Run Steampipe benchmark"
        id: steampipe-benchmark
        run: |

          # Install the Steampipe AWS Compliance mod
          steampipe mod install github.com/turbot/steampipe-mod-aws-compliance 
          cd .steampipe/mods/github.com/turbot/steampipe-mod-aws-compliance*
          # Run the AWS CIS v1.5.0 benchmark
          steampipe check benchmark.cis_v150 --export=steampipe_aws_cis_v150_"$(date +"%d_%B_%Y")".html --output=none

      - name: "Slack Notification"
        id: slack-upload
        env:
          slack_channel: ${{ secrets.OIDC_SLACK_CHANNEL_ID }}
          slack_token: ${{ secrets.OIDC_SLACK_OAUTH_ACCESS_TOKEN }}
        run: |

          cd .steampipe/mods/github.com/turbot/steampipe-mod-aws-compliance*
          curl -F file=@"steampipe_aws_cis_v150_"$(date +"%d_%B_%Y")".html" -F "initial_comment=Steampipe AWS CIS v150 Benchmark" -F "title=steampipe_aws_cis_v150_"$(date +"%d_%B_%Y")".html" -F channels=$slack_channel -H "Authorization: Bearer $slack_token " https://slack.com/api/files.upload -s -o /dev/null

      - name: Cleanup Steampipe files
        id: cleanup
        run: rm -rf ~/.steampipe && rm -rf .steampipe
